import type { ColorPalette } from "@/lib/wechat-editor/types";

export const WECHAT_COLOR_PALETTES: ColorPalette[] = [
  {
    id: "deskmate-coral",
    name: "Deskmate 珊瑚红",
    preview: "#FF5B5B,#FF8E8E,#FFF0F0",
    colors: {
      primary: "#FF5B5B",
      secondary: "#FF8E8E",
      accent: "#FF4747",
      background: "#ffffff",
      text: "#2f2230",
      onPrimary: "#ffffff",
      lightBg: "#FFF0F0",
      border: "#FFB1B1",
    },
  },
  {
    id: "blue-sky",
    name: "天空蓝",
    preview: "#1d4ed8,#60a5fa,#dbeafe",
    colors: {
      primary: "#1d4ed8",
      secondary: "#60a5fa",
      accent: "#2563eb",
      background: "#ffffff",
      text: "#1f2937",
      onPrimary: "#ffffff",
      lightBg: "#eff6ff",
      border: "#bfdbfe",
    },
  },
  {
    id: "orange-energy",
    name: "活力橙",
    preview: "#f97316,#fb923c,#ffedd5",
    colors: {
      primary: "#f97316",
      secondary: "#fb923c",
      accent: "#ea580c",
      background: "#fff7ed",
      text: "#3f2d1f",
      onPrimary: "#ffffff",
      lightBg: "#ffedd5",
      border: "#fdba74",
    },
  },
  {
    id: "green-campus",
    name: "校园绿",
    preview: "#16a34a,#4ade80,#dcfce7",
    colors: {
      primary: "#16a34a",
      secondary: "#4ade80",
      accent: "#22c55e",
      background: "#ffffff",
      text: "#14532d",
      onPrimary: "#ffffff",
      lightBg: "#f0fdf4",
      border: "#86efac",
    },
  },
  {
    id: "purple-premium",
    name: "高雅紫",
    preview: "#7c3aed,#a855f7,#f3e8ff",
    colors: {
      primary: "#7c3aed",
      secondary: "#a855f7",
      accent: "#9333ea",
      background: "#ffffff",
      text: "#3b0764",
      onPrimary: "#ffffff",
      lightBg: "#faf5ff",
      border: "#d8b4fe",
    },
  },
  {
    id: "pink-soft",
    name: "柔粉",
    preview: "#db2777,#f472b6,#ffe4e6",
    colors: {
      primary: "#db2777",
      secondary: "#f472b6",
      accent: "#ec4899",
      background: "#ffffff",
      text: "#831843",
      onPrimary: "#ffffff",
      lightBg: "#fff1f6",
      border: "#f9a8d4",
    },
  },
  {
    id: "red-festival",
    name: "节庆红",
    preview: "#dc2626,#ef4444,#fee2e2",
    colors: {
      primary: "#dc2626",
      secondary: "#ef4444",
      accent: "#b91c1c",
      background: "#fff5f5",
      text: "#7f1d1d",
      onPrimary: "#ffffff",
      lightBg: "#fee2e2",
      border: "#fca5a5",
    },
  },
  {
    id: "gray-minimal",
    name: "极简灰",
    preview: "#52525b,#a1a1aa,#f4f4f5",
    colors: {
      primary: "#52525b",
      secondary: "#a1a1aa",
      accent: "#71717a",
      background: "#ffffff",
      text: "#27272a",
      onPrimary: "#ffffff",
      lightBg: "#f4f4f5",
      border: "#d4d4d8",
    },
  },
  {
    id: "black-white",
    name: "黑白",
    preview: "#111827,#4b5563,#f9fafb",
    colors: {
      primary: "#111827",
      secondary: "#4b5563",
      accent: "#374151",
      background: "#ffffff",
      text: "#111827",
      onPrimary: "#ffffff",
      lightBg: "#f3f4f6",
      border: "#d1d5db",
    },
  },
  {
    id: "yellow-bright",
    name: "明亮黄",
    preview: "#ca8a04,#eab308,#fef9c3",
    colors: {
      primary: "#ca8a04",
      secondary: "#eab308",
      accent: "#a16207",
      background: "#ffffff",
      text: "#713f12",
      onPrimary: "#ffffff",
      lightBg: "#fef9c3",
      border: "#fde047",
    },
  },
  {
    id: "teal-fresh",
    name: "青绿",
    preview: "#0f766e,#14b8a6,#ccfbf1",
    colors: {
      primary: "#0f766e",
      secondary: "#14b8a6",
      accent: "#0d9488",
      background: "#ffffff",
      text: "#134e4a",
      onPrimary: "#ffffff",
      lightBg: "#ccfbf1",
      border: "#5eead4",
    },
  },
];

export function getPaletteById(id?: string | null) {
  if (!id) return WECHAT_COLOR_PALETTES[0];
  return WECHAT_COLOR_PALETTES.find((palette) => palette.id === id) ?? WECHAT_COLOR_PALETTES[0];
}
