-- wechat template expansion: 12 new templates
-- Style A (warm/pastel): warm-sunset, pastel-dream, honey-classroom, peach-blossom
-- Style B (blue/tech):    tech-frontier, sky-bulletin, indigo-insight, arctic-mono
-- Style C (red/gold):     ruby-gala, golden-phoenix, cherry-carnival, scarlet-press

insert into public.wechat_templates (
  id,
  name,
  thumbnail,
  categories,
  color_family,
  has_hero_image,
  color_scheme,
  block_styles,
  sort_order,
  is_active
) values
-- ============================================================
-- Style A: warm / pastel
-- ============================================================
(
  'warm-sunset',
  '暖阳落日',
  'https://dummyimage.com/480x640/fff7ed/c2410c&text=Warm+Sunset',
  array['活动', '温馨', '社团'],
  'orange',
  true,
  '{"primary":"#c2410c","secondary":"#fb923c","background":"#fffbf5","text":"#7c2d12","accent":"#f59e0b"}'::jsonb,
  $$[
    {"id":"warm-sunset-article-title","blockType":"article-title","name":"落日主标题","previewHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;text-shadow:0 2px 8px rgba(194,65,12,0.12);'>{{content}}</h1><p style='margin:8px auto 0;width:60px;height:3px;border-radius:2px;background:linear-gradient(90deg,{{color:primary}},{{color:accent}});'></p></section>","templateHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;text-shadow:0 2px 8px rgba(194,65,12,0.12);'>{{content}}</h1><p style='margin:8px auto 0;width:60px;height:3px;border-radius:2px;background:linear-gradient(90deg,{{color:primary}},{{color:accent}});'></p></section>"},
    {"id":"warm-sunset-hero-title","blockType":"hero-title","name":"暖光首屏","previewHtml":"<section style='padding:28px 20px;border-radius:18px;background:linear-gradient(135deg,#fff7ed,#ffedd5,#fef3c7);box-shadow:0 8px 24px rgba(251,146,60,0.15);'><h2 style='margin:0;font-size:24px;color:{{color:primary}};text-align:center;font-weight:700;'>{{content}}</h2></section>","templateHtml":"<section style='padding:28px 20px;border-radius:18px;background:linear-gradient(135deg,#fff7ed,#ffedd5,#fef3c7);box-shadow:0 8px 24px rgba(251,146,60,0.15);'><h2 style='margin:0;font-size:24px;color:{{color:primary}};text-align:center;font-weight:700;'>{{content}}</h2></section>"},
    {"id":"warm-sunset-hero-subtitle","blockType":"hero-subtitle","name":"暖光副标题","previewHtml":"<section style='margin-top:10px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;letter-spacing:1px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:10px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;letter-spacing:1px;'>{{content}}</p></section>"},
    {"id":"warm-sunset-intro","blockType":"intro","name":"暖阳引言","previewHtml":"<section style='margin:14px 0;padding:16px 18px;border-radius:14px;background:#fff7ed;box-shadow:0 4px 12px rgba(251,146,60,0.1);'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:16px 18px;border-radius:14px;background:#fff7ed;box-shadow:0 4px 12px rgba(251,146,60,0.1);'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"warm-sunset-section-title","blockType":"section-title","name":"日落小标题","previewHtml":"<section style='margin:22px 0 10px;'><h3 style='margin:0;display:inline-block;padding:6px 14px;border-radius:20px;background:linear-gradient(135deg,{{color:primary}},{{color:accent}});color:#fff;font-size:18px;box-shadow:0 4px 10px rgba(194,65,12,0.18);'>{{content}}</h3></section>","templateHtml":"<section style='margin:22px 0 10px;'><h3 style='margin:0;display:inline-block;padding:6px 14px;border-radius:20px;background:linear-gradient(135deg,{{color:primary}},{{color:accent}});color:#fff;font-size:18px;box-shadow:0 4px 10px rgba(194,65,12,0.18);'>{{content}}</h3></section>"},
    {"id":"warm-sunset-section-content","blockType":"section-content","name":"暖阳正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"warm-sunset-image","blockType":"image","name":"暖光配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:16px;box-shadow:0 8px 24px rgba(194,65,12,0.14);'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:16px;box-shadow:0 8px 24px rgba(194,65,12,0.14);'/>{{captionHtml}}</section>"},
    {"id":"warm-sunset-divider","blockType":"divider","name":"晚霞分割","previewHtml":"<section style='margin:22px 0;text-align:center;'><span style='display:inline-block;width:80px;height:3px;border-radius:2px;background:linear-gradient(90deg,transparent,{{color:secondary}},{{color:accent}},{{color:secondary}},transparent);'></span></section>","templateHtml":"<section style='margin:22px 0;text-align:center;'><span style='display:inline-block;width:80px;height:3px;border-radius:2px;background:linear-gradient(90deg,transparent,{{color:secondary}},{{color:accent}},{{color:secondary}},transparent);'></span></section>"},
    {"id":"warm-sunset-blockquote","blockType":"blockquote","name":"暖光引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;border-radius:12px;background:linear-gradient(135deg,#fff7ed,#fef3c7);border-left:4px solid {{color:accent}};box-shadow:0 2px 8px rgba(245,158,11,0.1);'><blockquote style='margin:0;color:{{color:text}};font-style:italic;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;border-radius:12px;background:linear-gradient(135deg,#fff7ed,#fef3c7);border-left:4px solid {{color:accent}};box-shadow:0 2px 8px rgba(245,158,11,0.1);'><blockquote style='margin:0;color:{{color:text}};font-style:italic;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  100,
  true
),
(
  'pastel-dream',
  '柔彩梦境',
  'https://dummyimage.com/480x640/fdf2f8/db2777&text=Pastel+Dream',
  array['校园', '少女', '文艺'],
  'pink',
  false,
  '{"primary":"#db2777","secondary":"#a78bfa","background":"#fefbff","text":"#831843","accent":"#e879f9"}'::jsonb,
  $$[
    {"id":"pastel-dream-article-title","blockType":"article-title","name":"梦境主标题","previewHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:700;'>{{content}}</h1><p style='margin:10px auto 0;width:40px;height:40px;border-radius:50%;background:radial-gradient(circle,#fbcfe8 30%,transparent 70%);opacity:0.5;'></p></section>","templateHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:700;'>{{content}}</h1><p style='margin:10px auto 0;width:40px;height:40px;border-radius:50%;background:radial-gradient(circle,#fbcfe8 30%,transparent 70%);opacity:0.5;'></p></section>"},
    {"id":"pastel-dream-hero-title","blockType":"hero-title","name":"梦幻首屏","previewHtml":"<section style='padding:24px 18px;border-radius:16px;background:linear-gradient(135deg,#fdf2f8,#fae8ff,#ede9fe);border:1px dashed {{color:secondary}};'><h2 style='margin:0;font-size:24px;color:{{color:primary}};text-align:center;'>{{content}}</h2></section>","templateHtml":"<section style='padding:24px 18px;border-radius:16px;background:linear-gradient(135deg,#fdf2f8,#fae8ff,#ede9fe);border:1px dashed {{color:secondary}};'><h2 style='margin:0;font-size:24px;color:{{color:primary}};text-align:center;'>{{content}}</h2></section>"},
    {"id":"pastel-dream-hero-subtitle","blockType":"hero-subtitle","name":"梦幻副标题","previewHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>{{content}}</p></section>"},
    {"id":"pastel-dream-intro","blockType":"intro","name":"梦境引言","previewHtml":"<section style='margin:14px 0;padding:14px 16px;border-radius:14px;background:#fdf2f8;border:1px dashed #f9a8d4;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:14px 16px;border-radius:14px;background:#fdf2f8;border:1px dashed #f9a8d4;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"pastel-dream-section-title","blockType":"section-title","name":"泡泡标题","previewHtml":"<section style='margin:20px 0 10px;display:flex;align-items:center;gap:8px;'><span style='display:inline-block;width:8px;height:8px;border-radius:50%;background:{{color:accent}};'></span><h3 style='margin:0;color:{{color:primary}};font-size:18px;'>{{content}}</h3><span style='display:inline-block;width:6px;height:6px;border-radius:50%;background:{{color:secondary}};opacity:0.6;'></span></section>","templateHtml":"<section style='margin:20px 0 10px;display:flex;align-items:center;gap:8px;'><span style='display:inline-block;width:8px;height:8px;border-radius:50%;background:{{color:accent}};'></span><h3 style='margin:0;color:{{color:primary}};font-size:18px;'>{{content}}</h3><span style='display:inline-block;width:6px;height:6px;border-radius:50%;background:{{color:secondary}};opacity:0.6;'></span></section>"},
    {"id":"pastel-dream-section-content","blockType":"section-content","name":"柔彩正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"pastel-dream-image","blockType":"image","name":"梦幻配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:14px;border:2px dashed #f9a8d4;padding:4px;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:14px;border:2px dashed #f9a8d4;padding:4px;'/>{{captionHtml}}</section>"},
    {"id":"pastel-dream-divider","blockType":"divider","name":"泡泡分割线","previewHtml":"<section style='margin:20px 0;text-align:center;'><span style='color:{{color:accent}};font-size:10px;letter-spacing:6px;'>○ ● ○ ● ○</span></section>","templateHtml":"<section style='margin:20px 0;text-align:center;'><span style='color:{{color:accent}};font-size:10px;letter-spacing:6px;'>○ ● ○ ● ○</span></section>"},
    {"id":"pastel-dream-blockquote","blockType":"blockquote","name":"梦境引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;border-radius:12px;background:linear-gradient(135deg,#fdf2f8,#fae8ff);border:1px dashed {{color:secondary}};'><blockquote style='margin:0;color:{{color:text}};'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;border-radius:12px;background:linear-gradient(135deg,#fdf2f8,#fae8ff);border:1px dashed {{color:secondary}};'><blockquote style='margin:0;color:{{color:text}};'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  110,
  true
),
(
  'honey-classroom',
  '蜜糖课堂',
  'https://dummyimage.com/480x640/fefce8/a16207&text=Honey+Classroom',
  array['教育', '课程', '亲子'],
  'yellow',
  true,
  '{"primary":"#a16207","secondary":"#f59e0b","background":"#fffef5","text":"#78350f","accent":"#d97706"}'::jsonb,
  $$[
    {"id":"honey-classroom-article-title","blockType":"article-title","name":"蜜糖主标题","previewHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;'>{{content}}</h1><p style='margin:8px auto 0;font-size:12px;color:{{color:secondary}};'>◇ ◇ ◇</p></section>","templateHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;'>{{content}}</h1><p style='margin:8px auto 0;font-size:12px;color:{{color:secondary}};'>◇ ◇ ◇</p></section>"},
    {"id":"honey-classroom-hero-title","blockType":"hero-title","name":"蜂巢首屏","previewHtml":"<section style='padding:24px 18px;border-radius:14px;background:#fef9c3;border:2px solid #fde68a;'><h2 style='margin:0;font-size:24px;color:{{color:primary}};text-align:center;font-weight:700;'>{{content}}</h2></section>","templateHtml":"<section style='padding:24px 18px;border-radius:14px;background:#fef9c3;border:2px solid #fde68a;'><h2 style='margin:0;font-size:24px;color:{{color:primary}};text-align:center;font-weight:700;'>{{content}}</h2></section>"},
    {"id":"honey-classroom-hero-subtitle","blockType":"hero-subtitle","name":"蜂巢副标题","previewHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:accent}};font-size:14px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:accent}};font-size:14px;'>{{content}}</p></section>"},
    {"id":"honey-classroom-intro","blockType":"intro","name":"蜜糖引言","previewHtml":"<section style='margin:14px 0;padding:14px 16px;border-radius:12px;background:#fefce8;border-left:5px solid {{color:secondary}};'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:14px 16px;border-radius:12px;background:#fefce8;border-left:5px solid {{color:secondary}};'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"honey-classroom-section-title","blockType":"section-title","name":"蜂巢标题","previewHtml":"<section style='margin:22px 0 10px;'><h3 style='margin:0;display:inline-block;padding:5px 14px;background:#fef9c3;border:2px solid {{color:secondary}};border-radius:8px;color:{{color:primary}};font-size:18px;'>{{content}}</h3></section>","templateHtml":"<section style='margin:22px 0 10px;'><h3 style='margin:0;display:inline-block;padding:5px 14px;background:#fef9c3;border:2px solid {{color:secondary}};border-radius:8px;color:{{color:primary}};font-size:18px;'>{{content}}</h3></section>"},
    {"id":"honey-classroom-section-content","blockType":"section-content","name":"蜜糖正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"honey-classroom-image","blockType":"image","name":"蜜糖配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:12px;border:2px solid #fde68a;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:12px;border:2px solid #fde68a;'/>{{captionHtml}}</section>"},
    {"id":"honey-classroom-divider","blockType":"divider","name":"蜂巢分割","previewHtml":"<section style='margin:20px 0;text-align:center;color:{{color:secondary}};font-size:14px;'>⬡ ⬡ ⬡</section>","templateHtml":"<section style='margin:20px 0;text-align:center;color:{{color:secondary}};font-size:14px;'>⬡ ⬡ ⬡</section>"},
    {"id":"honey-classroom-blockquote","blockType":"blockquote","name":"蜜糖引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;border-radius:10px;background:#fefce8;border:1px solid #fde68a;'><blockquote style='margin:0;color:{{color:text}};'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;border-radius:10px;background:#fefce8;border:1px solid #fde68a;'><blockquote style='margin:0;color:{{color:text}};'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  120,
  true
),
(
  'peach-blossom',
  '桃花信笺',
  'https://dummyimage.com/480x640/fff1f2/e11d48&text=Peach+Blossom',
  array['邀请', '优雅', '信笺'],
  'pink',
  false,
  '{"primary":"#e11d48","secondary":"#fb7185","background":"#fffbfc","text":"#9f1239","accent":"#f43f5e"}'::jsonb,
  $$[
    {"id":"peach-blossom-article-title","blockType":"article-title","name":"信笺主标题","previewHtml":"<section style='padding:20px 0;text-align:center;'><h1 style='margin:0;font-size:28px;line-height:1.4;color:{{color:primary}};font-weight:600;letter-spacing:2px;'>{{content}}</h1><p style='margin:10px auto 0;width:120px;border-top:1px solid #fda4af;border-bottom:1px solid #fda4af;padding:4px 0;text-align:center;font-size:10px;color:{{color:secondary}};letter-spacing:4px;'>❀</p></section>","templateHtml":"<section style='padding:20px 0;text-align:center;'><h1 style='margin:0;font-size:28px;line-height:1.4;color:{{color:primary}};font-weight:600;letter-spacing:2px;'>{{content}}</h1><p style='margin:10px auto 0;width:120px;border-top:1px solid #fda4af;border-bottom:1px solid #fda4af;padding:4px 0;text-align:center;font-size:10px;color:{{color:secondary}};letter-spacing:4px;'>❀</p></section>"},
    {"id":"peach-blossom-hero-title","blockType":"hero-title","name":"信笺首屏","previewHtml":"<section style='padding:22px 18px;border-radius:4px;background:#fff1f2;border:1px solid #fecdd3;border-top:3px double {{color:primary}};border-bottom:3px double {{color:primary}};'><h2 style='margin:0;font-size:22px;color:{{color:primary}};text-align:center;font-weight:600;letter-spacing:1px;'>{{content}}</h2></section>","templateHtml":"<section style='padding:22px 18px;border-radius:4px;background:#fff1f2;border:1px solid #fecdd3;border-top:3px double {{color:primary}};border-bottom:3px double {{color:primary}};'><h2 style='margin:0;font-size:22px;color:{{color:primary}};text-align:center;font-weight:600;letter-spacing:1px;'>{{content}}</h2></section>"},
    {"id":"peach-blossom-hero-subtitle","blockType":"hero-subtitle","name":"信笺副标题","previewHtml":"<section style='margin-top:10px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:13px;letter-spacing:2px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:10px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:13px;letter-spacing:2px;'>{{content}}</p></section>"},
    {"id":"peach-blossom-intro","blockType":"intro","name":"桃花引言","previewHtml":"<section style='margin:16px 0;padding:16px 18px;background:#fff;border:1px solid #fecdd3;border-radius:4px;border-left:none;border-right:none;border-left:1px solid #fecdd3;border-right:1px solid #fecdd3;'><p style='margin:0;font-size:16px;line-height:2;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:16px 0;padding:16px 18px;background:#fff;border:1px solid #fecdd3;border-radius:4px;border-left:none;border-right:none;border-left:1px solid #fecdd3;border-right:1px solid #fecdd3;'><p style='margin:0;font-size:16px;line-height:2;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"peach-blossom-section-title","blockType":"section-title","name":"花笺标题","previewHtml":"<section style='margin:22px 0 10px;text-align:center;'><h3 style='margin:0;display:inline-block;padding:4px 20px;color:{{color:primary}};font-size:18px;font-weight:600;border-bottom:1px solid {{color:secondary}};letter-spacing:1px;'>{{content}}</h3></section>","templateHtml":"<section style='margin:22px 0 10px;text-align:center;'><h3 style='margin:0;display:inline-block;padding:4px 20px;color:{{color:primary}};font-size:18px;font-weight:600;border-bottom:1px solid {{color:secondary}};letter-spacing:1px;'>{{content}}</h3></section>"},
    {"id":"peach-blossom-section-content","blockType":"section-content","name":"信笺正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:2;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:2;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"peach-blossom-image","blockType":"image","name":"信笺配图","previewHtml":"<section style='margin:18px 0;text-align:center;padding:6px;border:1px solid #fecdd3;border-radius:4px;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:2px;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;padding:6px;border:1px solid #fecdd3;border-radius:4px;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:2px;'/>{{captionHtml}}</section>"},
    {"id":"peach-blossom-divider","blockType":"divider","name":"花瓣分割","previewHtml":"<section style='margin:22px 0;text-align:center;'><span style='color:{{color:secondary}};font-size:12px;letter-spacing:8px;'>— ❀ —</span></section>","templateHtml":"<section style='margin:22px 0;text-align:center;'><span style='color:{{color:secondary}};font-size:12px;letter-spacing:8px;'>— ❀ —</span></section>"},
    {"id":"peach-blossom-blockquote","blockType":"blockquote","name":"花笺引用","previewHtml":"<section style='margin:16px 0;padding:14px 18px;background:#fff1f2;border-top:1px solid #fda4af;border-bottom:1px solid #fda4af;'><blockquote style='margin:0;color:{{color:text}};font-style:italic;text-align:center;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 18px;background:#fff1f2;border-top:1px solid #fda4af;border-bottom:1px solid #fda4af;'><blockquote style='margin:0;color:{{color:text}};font-style:italic;text-align:center;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  130,
  true
),
-- ============================================================
-- Style B: blue / tech
-- ============================================================
(
  'tech-frontier',
  '科技前沿',
  'https://dummyimage.com/480x640/0c1e3a/00d4ff&text=Tech+Frontier',
  array['科技', '前沿', '数码'],
  'blue',
  true,
  '{"primary":"#0a2540","secondary":"#00d4ff","background":"#f0f7ff","text":"#1a2b3c","accent":"#00b4d8"}'::jsonb,
  $$[
    {"id":"tech-frontier-article-title","blockType":"article-title","name":"科技主标题","previewHtml":"<section style='padding:18px 0 12px;position:relative;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;letter-spacing:1px;'>{{content}}</h1><div style='margin-top:8px;height:3px;width:80px;background:linear-gradient(90deg,{{color:secondary}},transparent);'></div></section>","templateHtml":"<section style='padding:18px 0 12px;position:relative;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;letter-spacing:1px;'>{{content}}</h1><div style='margin-top:8px;height:3px;width:80px;background:linear-gradient(90deg,{{color:secondary}},transparent);'></div></section>"},
    {"id":"tech-frontier-hero-title","blockType":"hero-title","name":"科技首屏标题","previewHtml":"<section style='padding:24px 18px;background:linear-gradient(135deg,#0a2540,#163a5f);border-radius:10px;border:1px solid rgba(0,212,255,0.3);'><h2 style='margin:0;font-size:24px;color:#00d4ff;text-align:center;'>{{content}}</h2></section>","templateHtml":"<section style='padding:24px 18px;background:linear-gradient(135deg,#0a2540,#163a5f);border-radius:10px;border:1px solid rgba(0,212,255,0.3);'><h2 style='margin:0;font-size:24px;color:#00d4ff;text-align:center;'>{{content}}</h2></section>"},
    {"id":"tech-frontier-hero-subtitle","blockType":"hero-subtitle","name":"科技副标题","previewHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:13px;letter-spacing:2px;text-transform:uppercase;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:13px;letter-spacing:2px;text-transform:uppercase;'>{{content}}</p></section>"},
    {"id":"tech-frontier-intro","blockType":"intro","name":"科技导语","previewHtml":"<section style='margin:14px 0;padding:14px 16px;background:linear-gradient(135deg,#e8f4fd,#f0f7ff);border-left:3px solid {{color:secondary}};border-radius:0 8px 8px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:14px 16px;background:linear-gradient(135deg,#e8f4fd,#f0f7ff);border-left:3px solid {{color:secondary}};border-radius:0 8px 8px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"tech-frontier-section-title","blockType":"section-title","name":"几何标题","previewHtml":"<section style='margin:22px 0 10px;display:flex;align-items:center;gap:10px;'><span style='display:inline-block;width:8px;height:8px;background:{{color:secondary}};transform:rotate(45deg);'></span><h3 style='margin:0;font-size:20px;color:{{color:primary}};font-weight:700;'>{{content}}</h3></section>","templateHtml":"<section style='margin:22px 0 10px;display:flex;align-items:center;gap:10px;'><span style='display:inline-block;width:8px;height:8px;background:{{color:secondary}};transform:rotate(45deg);'></span><h3 style='margin:0;font-size:20px;color:{{color:primary}};font-weight:700;'>{{content}}</h3></section>"},
    {"id":"tech-frontier-section-content","blockType":"section-content","name":"科技正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"tech-frontier-image","blockType":"image","name":"科技配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:8px;border:1px solid rgba(0,212,255,0.2);'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:8px;border:1px solid rgba(0,212,255,0.2);'/>{{captionHtml}}</section>"},
    {"id":"tech-frontier-divider","blockType":"divider","name":"电路分割线","previewHtml":"<section style='margin:20px 0;text-align:center;'><span style='display:inline-block;width:120px;height:2px;background:linear-gradient(90deg,transparent,{{color:secondary}},{{color:secondary}},transparent);'></span></section>","templateHtml":"<section style='margin:20px 0;text-align:center;'><span style='display:inline-block;width:120px;height:2px;background:linear-gradient(90deg,transparent,{{color:secondary}},{{color:secondary}},transparent);'></span></section>"},
    {"id":"tech-frontier-blockquote","blockType":"blockquote","name":"终端引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;background:#0a2540;border-radius:8px;border:1px solid rgba(0,212,255,0.25);'><blockquote style='margin:0;color:#00d4ff;font-family:monospace;font-size:15px;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;background:#0a2540;border-radius:8px;border:1px solid rgba(0,212,255,0.25);'><blockquote style='margin:0;color:#00d4ff;font-family:monospace;font-size:15px;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  200,
  true
),
(
  'sky-bulletin',
  '天空简报',
  'https://dummyimage.com/480x640/e0f2fe/0369a1&text=Sky+Bulletin',
  array['资讯', '简报', '校园'],
  'blue',
  true,
  '{"primary":"#0369a1","secondary":"#7dd3fc","background":"#f0f9ff","text":"#0c4a6e","accent":"#0ea5e9"}'::jsonb,
  $$[
    {"id":"sky-bulletin-article-title","blockType":"article-title","name":"简报主标题","previewHtml":"<section style='padding:16px 0 10px;border-bottom:2px solid {{color:accent}};'><h1 style='margin:0;font-size:28px;line-height:1.35;color:{{color:primary}};font-weight:700;'>{{content}}</h1></section>","templateHtml":"<section style='padding:16px 0 10px;border-bottom:2px solid {{color:accent}};'><h1 style='margin:0;font-size:28px;line-height:1.35;color:{{color:primary}};font-weight:700;'>{{content}}</h1></section>"},
    {"id":"sky-bulletin-hero-title","blockType":"hero-title","name":"简报首屏","previewHtml":"<section style='padding:22px 18px;background:#f0f9ff;border:2px solid #bae6fd;border-radius:10px;'><h2 style='margin:0;font-size:22px;color:{{color:primary}};'>{{content}}</h2></section>","templateHtml":"<section style='padding:22px 18px;background:#f0f9ff;border:2px solid #bae6fd;border-radius:10px;'><h2 style='margin:0;font-size:22px;color:{{color:primary}};'>{{content}}</h2></section>"},
    {"id":"sky-bulletin-hero-subtitle","blockType":"hero-subtitle","name":"简报副标题","previewHtml":"<section style='margin-top:8px;padding:6px 14px;'><p style='margin:0;color:{{color:primary}};font-size:14px;opacity:0.75;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:8px;padding:6px 14px;'><p style='margin:0;color:{{color:primary}};font-size:14px;opacity:0.75;'>{{content}}</p></section>"},
    {"id":"sky-bulletin-intro","blockType":"intro","name":"简报导语","previewHtml":"<section style='margin:14px 0;padding:14px 16px;background:#fff;border:1px solid #bae6fd;border-radius:8px;'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:14px 16px;background:#fff;border:1px solid #bae6fd;border-radius:8px;'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"sky-bulletin-section-title","blockType":"section-title","name":"栏目标题","previewHtml":"<section style='margin:20px 0 10px;padding:6px 14px;background:#e0f2fe;border-radius:6px;display:inline-block;'><h3 style='margin:0;font-size:18px;color:{{color:primary}};font-weight:600;'>{{content}}</h3></section>","templateHtml":"<section style='margin:20px 0 10px;padding:6px 14px;background:#e0f2fe;border-radius:6px;display:inline-block;'><h3 style='margin:0;font-size:18px;color:{{color:primary}};font-weight:600;'>{{content}}</h3></section>"},
    {"id":"sky-bulletin-section-content","blockType":"section-content","name":"简报正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"sky-bulletin-image","blockType":"image","name":"简报配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:8px;border:1px solid #bae6fd;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:8px;border:1px solid #bae6fd;'/>{{captionHtml}}</section>"},
    {"id":"sky-bulletin-divider","blockType":"divider","name":"简报分隔","previewHtml":"<section style='margin:18px 0;border-top:1px dashed #bae6fd;'></section>","templateHtml":"<section style='margin:18px 0;border-top:1px dashed #bae6fd;'></section>"},
    {"id":"sky-bulletin-blockquote","blockType":"blockquote","name":"简报引用","previewHtml":"<section style='margin:16px 0;padding:12px 14px;background:#f0f9ff;border-left:4px solid {{color:accent}};border-radius:0 6px 6px 0;'><blockquote style='margin:0;color:{{color:text}};font-size:15px;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:12px 14px;background:#f0f9ff;border-left:4px solid {{color:accent}};border-radius:0 6px 6px 0;'><blockquote style='margin:0;color:{{color:text}};font-size:15px;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  210,
  true
),
(
  'indigo-insight',
  '靛蓝洞察',
  'https://dummyimage.com/480x640/e0e7ff/4338ca&text=Indigo+Insight',
  array['数据', '报告', '深度'],
  'purple',
  false,
  '{"primary":"#4338ca","secondary":"#818cf8","background":"#eef2ff","text":"#312e81","accent":"#6366f1"}'::jsonb,
  $$[
    {"id":"indigo-insight-article-title","blockType":"article-title","name":"洞察主标题","previewHtml":"<section style='padding:18px 0 10px;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;'>{{content}}</h1><div style='margin-top:10px;display:flex;gap:4px;'><span style='display:inline-block;width:24px;height:4px;background:{{color:primary}};border-radius:2px;'></span><span style='display:inline-block;width:12px;height:4px;background:{{color:secondary}};border-radius:2px;'></span><span style='display:inline-block;width:6px;height:4px;background:{{color:accent}};border-radius:2px;'></span></div></section>","templateHtml":"<section style='padding:18px 0 10px;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;'>{{content}}</h1><div style='margin-top:10px;display:flex;gap:4px;'><span style='display:inline-block;width:24px;height:4px;background:{{color:primary}};border-radius:2px;'></span><span style='display:inline-block;width:12px;height:4px;background:{{color:secondary}};border-radius:2px;'></span><span style='display:inline-block;width:6px;height:4px;background:{{color:accent}};border-radius:2px;'></span></div></section>"},
    {"id":"indigo-insight-hero-title","blockType":"hero-title","name":"数据首屏","previewHtml":"<section style='padding:22px 18px;background:linear-gradient(145deg,#eef2ff,#e0e7ff);border-radius:12px;border:1px solid #c7d2fe;'><h2 style='margin:0;font-size:23px;color:{{color:primary}};'>{{content}}</h2></section>","templateHtml":"<section style='padding:22px 18px;background:linear-gradient(145deg,#eef2ff,#e0e7ff);border-radius:12px;border:1px solid #c7d2fe;'><h2 style='margin:0;font-size:23px;color:{{color:primary}};'>{{content}}</h2></section>"},
    {"id":"indigo-insight-hero-subtitle","blockType":"hero-subtitle","name":"数据副标题","previewHtml":"<section style='margin-top:8px;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:8px;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>{{content}}</p></section>"},
    {"id":"indigo-insight-intro","blockType":"intro","name":"数据导语","previewHtml":"<section style='margin:14px 0;padding:16px;background:#fff;border-radius:10px;border:1px solid #c7d2fe;box-shadow:0 2px 8px rgba(67,56,202,0.08);'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:16px;background:#fff;border-radius:10px;border:1px solid #c7d2fe;box-shadow:0 2px 8px rgba(67,56,202,0.08);'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"indigo-insight-section-title","blockType":"section-title","name":"指标标题","previewHtml":"<section style='margin:22px 0 10px;display:flex;align-items:center;gap:10px;'><span style='display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;background:{{color:primary}};color:#fff;font-size:13px;font-weight:700;border-radius:6px;'>§</span><h3 style='margin:0;font-size:19px;color:{{color:primary}};font-weight:700;'>{{content}}</h3></section>","templateHtml":"<section style='margin:22px 0 10px;display:flex;align-items:center;gap:10px;'><span style='display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;background:{{color:primary}};color:#fff;font-size:13px;font-weight:700;border-radius:6px;'>§</span><h3 style='margin:0;font-size:19px;color:{{color:primary}};font-weight:700;'>{{content}}</h3></section>"},
    {"id":"indigo-insight-section-content","blockType":"section-content","name":"洞察正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"indigo-insight-image","blockType":"image","name":"数据配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:10px;border:1px solid #c7d2fe;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:10px;border:1px solid #c7d2fe;'/>{{captionHtml}}</section>"},
    {"id":"indigo-insight-divider","blockType":"divider","name":"数据分割","previewHtml":"<section style='margin:20px 0;display:flex;align-items:center;gap:8px;justify-content:center;'><span style='display:inline-block;width:6px;height:6px;background:{{color:primary}};border-radius:50%;'></span><span style='display:inline-block;width:40px;height:1px;background:#c7d2fe;'></span><span style='display:inline-block;width:6px;height:6px;background:{{color:secondary}};border-radius:50%;'></span><span style='display:inline-block;width:40px;height:1px;background:#c7d2fe;'></span><span style='display:inline-block;width:6px;height:6px;background:{{color:accent}};border-radius:50%;'></span></section>","templateHtml":"<section style='margin:20px 0;display:flex;align-items:center;gap:8px;justify-content:center;'><span style='display:inline-block;width:6px;height:6px;background:{{color:primary}};border-radius:50%;'></span><span style='display:inline-block;width:40px;height:1px;background:#c7d2fe;'></span><span style='display:inline-block;width:6px;height:6px;background:{{color:secondary}};border-radius:50%;'></span><span style='display:inline-block;width:40px;height:1px;background:#c7d2fe;'></span><span style='display:inline-block;width:6px;height:6px;background:{{color:accent}};border-radius:50%;'></span></section>"},
    {"id":"indigo-insight-blockquote","blockType":"blockquote","name":"洞察引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;background:#eef2ff;border-radius:8px;border:1px solid #c7d2fe;'><blockquote style='margin:0;color:{{color:primary}};font-size:15px;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;background:#eef2ff;border-radius:8px;border:1px solid #c7d2fe;'><blockquote style='margin:0;color:{{color:primary}};font-size:15px;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  220,
  true
),
(
  'arctic-mono',
  '极光清简',
  'https://dummyimage.com/480x640/f1f5f9/475569&text=Arctic+Mono',
  array['极简', '学术', '报告'],
  'gray',
  false,
  '{"primary":"#334155","secondary":"#94a3b8","background":"#f8fafc","text":"#475569","accent":"#64748b"}'::jsonb,
  $$[
    {"id":"arctic-mono-article-title","blockType":"article-title","name":"学术主标题","previewHtml":"<section style='padding:20px 0 14px;'><h1 style='margin:0;font-size:28px;line-height:1.4;color:{{color:primary}};font-weight:700;letter-spacing:0.5px;'>{{content}}</h1><div style='margin-top:12px;height:1px;background:{{color:secondary}};'></div></section>","templateHtml":"<section style='padding:20px 0 14px;'><h1 style='margin:0;font-size:28px;line-height:1.4;color:{{color:primary}};font-weight:700;letter-spacing:0.5px;'>{{content}}</h1><div style='margin-top:12px;height:1px;background:{{color:secondary}};'></div></section>"},
    {"id":"arctic-mono-hero-title","blockType":"hero-title","name":"报告首屏","previewHtml":"<section style='padding:20px 16px;border:1px solid #cbd5e1;border-radius:6px;'><h2 style='margin:0;font-size:22px;color:{{color:primary}};'>{{content}}</h2></section>","templateHtml":"<section style='padding:20px 16px;border:1px solid #cbd5e1;border-radius:6px;'><h2 style='margin:0;font-size:22px;color:{{color:primary}};'>{{content}}</h2></section>"},
    {"id":"arctic-mono-hero-subtitle","blockType":"hero-subtitle","name":"报告副标题","previewHtml":"<section style='margin-top:6px;padding:0 16px;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:6px;padding:0 16px;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>{{content}}</p></section>"},
    {"id":"arctic-mono-intro","blockType":"intro","name":"摘要引言","previewHtml":"<section style='margin:16px 0;padding:14px 16px;background:#f1f5f9;border-radius:4px;'><p style='margin:0;font-size:15px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;background:#f1f5f9;border-radius:4px;'><p style='margin:0;font-size:15px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"arctic-mono-section-title","blockType":"section-title","name":"章节标题","previewHtml":"<section style='margin:24px 0 10px;padding:0 0 6px 12px;border-left:3px solid {{color:primary}};border-bottom:2px solid #e2e8f0;'><h3 style='margin:0;font-size:18px;color:{{color:primary}};font-weight:600;'>{{content}}</h3></section>","templateHtml":"<section style='margin:24px 0 10px;padding:0 0 6px 12px;border-left:3px solid {{color:primary}};border-bottom:2px solid #e2e8f0;'><h3 style='margin:0;font-size:18px;color:{{color:primary}};font-weight:600;'>{{content}}</h3></section>"},
    {"id":"arctic-mono-section-content","blockType":"section-content","name":"学术正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.95;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.95;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"arctic-mono-image","blockType":"image","name":"学术配图","previewHtml":"<section style='margin:20px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:4px;border:1px solid #e2e8f0;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:20px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:4px;border:1px solid #e2e8f0;'/>{{captionHtml}}</section>"},
    {"id":"arctic-mono-divider","blockType":"divider","name":"学术分割","previewHtml":"<section style='margin:22px 0;'><hr style='border:none;border-top:1px solid #e2e8f0;'/></section>","templateHtml":"<section style='margin:22px 0;'><hr style='border:none;border-top:1px solid #e2e8f0;'/></section>"},
    {"id":"arctic-mono-blockquote","blockType":"blockquote","name":"学术引用","previewHtml":"<section style='margin:16px 0;padding:12px 16px;background:#f1f5f9;border-left:3px solid {{color:primary}};border-radius:4px;'><blockquote style='margin:0;color:{{color:text}};font-size:15px;line-height:1.8;font-style:italic;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:12px 16px;background:#f1f5f9;border-left:3px solid {{color:primary}};border-radius:4px;'><blockquote style='margin:0;color:{{color:text}};font-size:15px;line-height:1.8;font-style:italic;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  230,
  true
),
-- ============================================================
-- Style C: red / gold
-- ============================================================
(
  'ruby-gala',
  '红宝盛典',
  'https://dummyimage.com/480x640/7a0f24/d4a843&text=Ruby+Gala',
  array['盛典', '典礼', '表彰'],
  'red',
  true,
  '{"primary":"#9b1b30","secondary":"#d4a843","background":"#fef9f4","text":"#4a1020","accent":"#c5a55a"}'::jsonb,
  $$[
    {"id":"ruby-gala-article-title","blockType":"article-title","name":"盛典主标题","previewHtml":"<section style='padding:20px 0 12px;text-align:center;border-top:3px double {{color:secondary}};border-bottom:3px double {{color:secondary}};'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;letter-spacing:2px;'>{{content}}</h1></section>","templateHtml":"<section style='padding:20px 0 12px;text-align:center;border-top:3px double {{color:secondary}};border-bottom:3px double {{color:secondary}};'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;letter-spacing:2px;'>{{content}}</h1></section>"},
    {"id":"ruby-gala-hero-title","blockType":"hero-title","name":"典礼首屏","previewHtml":"<section style='padding:24px 18px;background:linear-gradient(135deg,#9b1b30,#7a0f24);border:2px solid {{color:secondary}};border-radius:8px;'><h2 style='margin:0;font-size:24px;color:{{color:secondary}};text-align:center;letter-spacing:1px;'>{{content}}</h2></section>","templateHtml":"<section style='padding:24px 18px;background:linear-gradient(135deg,#9b1b30,#7a0f24);border:2px solid {{color:secondary}};border-radius:8px;'><h2 style='margin:0;font-size:24px;color:{{color:secondary}};text-align:center;letter-spacing:1px;'>{{content}}</h2></section>"},
    {"id":"ruby-gala-hero-subtitle","blockType":"hero-subtitle","name":"典礼副标题","previewHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;letter-spacing:3px;'>{{content}}</p></section>","templateHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;letter-spacing:3px;'>{{content}}</p></section>"},
    {"id":"ruby-gala-intro","blockType":"intro","name":"盛典引言","previewHtml":"<section style='margin:14px 0;padding:16px;background:#fef3e8;border:1px solid {{color:secondary}};border-radius:6px;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:16px;background:#fef3e8;border:1px solid {{color:secondary}};border-radius:6px;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"ruby-gala-section-title","blockType":"section-title","name":"金框小标题","previewHtml":"<section style='margin:20px 0 10px;'><h3 style='margin:0;display:inline-block;padding:6px 16px;border:2px solid {{color:secondary}};color:{{color:primary}};font-size:19px;font-weight:700;'>{{content}}</h3></section>","templateHtml":"<section style='margin:20px 0 10px;'><h3 style='margin:0;display:inline-block;padding:6px 16px;border:2px solid {{color:secondary}};color:{{color:primary}};font-size:19px;font-weight:700;'>{{content}}</h3></section>"},
    {"id":"ruby-gala-section-content","blockType":"section-content","name":"盛典正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"ruby-gala-image","blockType":"image","name":"典礼配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:6px;border:2px solid {{color:secondary}};'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:6px;border:2px solid {{color:secondary}};'/>{{captionHtml}}</section>"},
    {"id":"ruby-gala-divider","blockType":"divider","name":"金色双线","previewHtml":"<section style='margin:20px 0;text-align:center;'><span style='display:inline-block;width:120px;border-top:1px solid {{color:secondary}};border-bottom:1px solid {{color:secondary}};height:4px;'></span></section>","templateHtml":"<section style='margin:20px 0;text-align:center;'><span style='display:inline-block;width:120px;border-top:1px solid {{color:secondary}};border-bottom:1px solid {{color:secondary}};height:4px;'></span></section>"},
    {"id":"ruby-gala-blockquote","blockType":"blockquote","name":"红金引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;background:#fef3e8;border-left:4px solid {{color:secondary}};border-right:4px solid {{color:secondary}};'><blockquote style='margin:0;color:{{color:primary}};font-style:italic;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;background:#fef3e8;border-left:4px solid {{color:secondary}};border-right:4px solid {{color:secondary}};'><blockquote style='margin:0;color:{{color:primary}};font-style:italic;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  300,
  true
),
(
  'golden-phoenix',
  '金凤华章',
  'https://dummyimage.com/480x640/b8860b/cc3333&text=Golden+Phoenix',
  array['节庆', '传统', '贺年'],
  'yellow',
  true,
  '{"primary":"#b8860b","secondary":"#cc3333","background":"#fdf8ee","text":"#5c2e0e","accent":"#d4a017"}'::jsonb,
  $$[
    {"id":"golden-phoenix-article-title","blockType":"article-title","name":"华章主标题","previewHtml":"<section style='padding:20px 16px;text-align:center;background:linear-gradient(180deg,#fdf8ee,#f5e6c8);'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:secondary}};font-weight:800;'>◈ {{content}} ◈</h1></section>","templateHtml":"<section style='padding:20px 16px;text-align:center;background:linear-gradient(180deg,#fdf8ee,#f5e6c8);'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:secondary}};font-weight:800;'>◈ {{content}} ◈</h1></section>"},
    {"id":"golden-phoenix-hero-title","blockType":"hero-title","name":"国潮首屏","previewHtml":"<section style='padding:24px 18px;background:{{color:secondary}};border-radius:4px;border:3px solid {{color:primary}};position:relative;'><h2 style='margin:0;font-size:24px;color:#fdf1c0;text-align:center;letter-spacing:2px;'>{{content}}</h2></section>","templateHtml":"<section style='padding:24px 18px;background:{{color:secondary}};border-radius:4px;border:3px solid {{color:primary}};position:relative;'><h2 style='margin:0;font-size:24px;color:#fdf1c0;text-align:center;letter-spacing:2px;'>{{content}}</h2></section>"},
    {"id":"golden-phoenix-hero-subtitle","blockType":"hero-subtitle","name":"国潮副标题","previewHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:primary}};font-size:14px;letter-spacing:4px;'>〔 {{content}} 〕</p></section>","templateHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:primary}};font-size:14px;letter-spacing:4px;'>〔 {{content}} 〕</p></section>"},
    {"id":"golden-phoenix-intro","blockType":"intro","name":"华章引言","previewHtml":"<section style='margin:14px 0;padding:16px;background:#fdf1c0;border-top:2px solid {{color:primary}};border-bottom:2px solid {{color:primary}};'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:16px;background:#fdf1c0;border-top:2px solid {{color:primary}};border-bottom:2px solid {{color:primary}};'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"golden-phoenix-section-title","blockType":"section-title","name":"回纹标题","previewHtml":"<section style='margin:20px 0 10px;padding:6px 14px;background:{{color:primary}};display:inline-block;'><h3 style='margin:0;color:#fff;font-size:19px;font-weight:700;'>{{content}}</h3></section>","templateHtml":"<section style='margin:20px 0 10px;padding:6px 14px;background:{{color:primary}};display:inline-block;'><h3 style='margin:0;color:#fff;font-size:19px;font-weight:700;'>{{content}}</h3></section>"},
    {"id":"golden-phoenix-section-content","blockType":"section-content","name":"华章正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"golden-phoenix-image","blockType":"image","name":"锦绣配图","previewHtml":"<section style='margin:18px 0;text-align:center;padding:8px;background:#fdf1c0;border:1px solid {{color:primary}};'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:2px;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;padding:8px;background:#fdf1c0;border:1px solid {{color:primary}};'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:2px;'/>{{captionHtml}}</section>"},
    {"id":"golden-phoenix-divider","blockType":"divider","name":"回纹分割","previewHtml":"<section style='margin:20px 0;text-align:center;color:{{color:primary}};font-size:14px;letter-spacing:6px;'>◇◆◇◆◇</section>","templateHtml":"<section style='margin:20px 0;text-align:center;color:{{color:primary}};font-size:14px;letter-spacing:6px;'>◇◆◇◆◇</section>"},
    {"id":"golden-phoenix-blockquote","blockType":"blockquote","name":"朱金引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;background:#fef8ee;border:1px solid {{color:primary}};border-left:5px solid {{color:secondary}};'><blockquote style='margin:0;color:{{color:secondary}};'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;background:#fef8ee;border:1px solid {{color:primary}};border-left:5px solid {{color:secondary}};'><blockquote style='margin:0;color:{{color:secondary}};'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  310,
  true
),
(
  'cherry-carnival',
  '樱桃嘉年华',
  'https://dummyimage.com/480x640/dc143c/ffb6c1&text=Cherry+Carnival',
  array['嘉年华', '促销', '趣味'],
  'red',
  false,
  '{"primary":"#dc143c","secondary":"#ff69b4","background":"#fff5f7","text":"#6b1631","accent":"#ff1493"}'::jsonb,
  $$[
    {"id":"cherry-carnival-article-title","blockType":"article-title","name":"嘉年华主标题","previewHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;'>🎉 {{content}} 🎉</h1></section>","templateHtml":"<section style='padding:18px 0;text-align:center;'><h1 style='margin:0;font-size:30px;line-height:1.35;color:{{color:primary}};font-weight:800;'>🎉 {{content}} 🎉</h1></section>"},
    {"id":"cherry-carnival-hero-title","blockType":"hero-title","name":"狂欢标题","previewHtml":"<section style='padding:22px 16px;background:linear-gradient(135deg,{{color:primary}},{{color:accent}});border-radius:16px;'><h2 style='margin:0;font-size:24px;color:#fff;text-align:center;'>{{content}}</h2></section>","templateHtml":"<section style='padding:22px 16px;background:linear-gradient(135deg,{{color:primary}},{{color:accent}});border-radius:16px;'><h2 style='margin:0;font-size:24px;color:#fff;text-align:center;'>{{content}}</h2></section>"},
    {"id":"cherry-carnival-hero-subtitle","blockType":"hero-subtitle","name":"狂欢副标题","previewHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>✨ {{content}} ✨</p></section>","templateHtml":"<section style='margin-top:8px;text-align:center;'><p style='margin:0;color:{{color:secondary}};font-size:14px;'>✨ {{content}} ✨</p></section>"},
    {"id":"cherry-carnival-intro","blockType":"intro","name":"嘉年华引言","previewHtml":"<section style='margin:14px 0;padding:14px;border-radius:14px;background:#fff0f3;border:2px dashed {{color:secondary}};'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:14px;border-radius:14px;background:#fff0f3;border:2px dashed {{color:secondary}};'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"cherry-carnival-section-title","blockType":"section-title","name":"气球标题","previewHtml":"<section style='margin:20px 0 10px;'><h3 style='margin:0;display:inline-block;padding:6px 16px;border-radius:999px;background:{{color:primary}};color:#fff;font-size:18px;'>🎈 {{content}}</h3></section>","templateHtml":"<section style='margin:20px 0 10px;'><h3 style='margin:0;display:inline-block;padding:6px 16px;border-radius:999px;background:{{color:primary}};color:#fff;font-size:18px;'>🎈 {{content}}</h3></section>"},
    {"id":"cherry-carnival-section-content","blockType":"section-content","name":"嘉年华正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};'>{{content}}</p></section>"},
    {"id":"cherry-carnival-image","blockType":"image","name":"派对配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:16px;box-shadow:0 6px 18px rgba(220,20,60,0.2);'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:16px;box-shadow:0 6px 18px rgba(220,20,60,0.2);'/>{{captionHtml}}</section>"},
    {"id":"cherry-carnival-divider","blockType":"divider","name":"彩带分割","previewHtml":"<section style='margin:20px 0;text-align:center;font-size:14px;'>🎀🎊🎀🎊🎀</section>","templateHtml":"<section style='margin:20px 0;text-align:center;font-size:14px;'>🎀🎊🎀🎊🎀</section>"},
    {"id":"cherry-carnival-blockquote","blockType":"blockquote","name":"彩虹引用","previewHtml":"<section style='margin:16px 0;padding:14px;border-radius:12px;background:linear-gradient(135deg,#fff0f3,#ffe0eb);'><blockquote style='margin:0;color:{{color:primary}};font-weight:600;'>🌟 {{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px;border-radius:12px;background:linear-gradient(135deg,#fff0f3,#ffe0eb);'><blockquote style='margin:0;color:{{color:primary}};font-weight:600;'>🌟 {{content}}</blockquote></section>"}
  ]$$::jsonb,
  320,
  true
),
(
  'scarlet-press',
  '绯红新闻',
  'https://dummyimage.com/480x640/cc0000/1a1a2e&text=Scarlet+Press',
  array['新闻', '发布', '官方'],
  'red',
  false,
  '{"primary":"#cc0000","secondary":"#1a1a2e","background":"#ffffff","text":"#1a1a2e","accent":"#e60000"}'::jsonb,
  $$[
    {"id":"scarlet-press-article-title","blockType":"article-title","name":"头条标题","previewHtml":"<section style='padding:18px 0 10px;border-bottom:4px solid {{color:primary}};'><h1 style='margin:0;font-size:32px;line-height:1.3;color:{{color:secondary}};font-weight:900;text-transform:uppercase;'>{{content}}</h1></section>","templateHtml":"<section style='padding:18px 0 10px;border-bottom:4px solid {{color:primary}};'><h1 style='margin:0;font-size:32px;line-height:1.3;color:{{color:secondary}};font-weight:900;text-transform:uppercase;'>{{content}}</h1></section>"},
    {"id":"scarlet-press-hero-title","blockType":"hero-title","name":"新闻首屏","previewHtml":"<section style='padding:20px 16px;background:{{color:secondary}};'><h2 style='margin:0;font-size:24px;color:#fff;font-weight:800;'>{{content}}</h2></section>","templateHtml":"<section style='padding:20px 16px;background:{{color:secondary}};'><h2 style='margin:0;font-size:24px;color:#fff;font-weight:800;'>{{content}}</h2></section>"},
    {"id":"scarlet-press-hero-subtitle","blockType":"hero-subtitle","name":"新闻副标题","previewHtml":"<section style='padding:8px 16px;background:{{color:primary}};'><p style='margin:0;color:#fff;font-size:14px;font-weight:600;'>{{content}}</p></section>","templateHtml":"<section style='padding:8px 16px;background:{{color:primary}};'><p style='margin:0;color:#fff;font-size:14px;font-weight:600;'>{{content}}</p></section>"},
    {"id":"scarlet-press-intro","blockType":"intro","name":"新闻导语","previewHtml":"<section style='margin:14px 0;padding:14px 16px;background:#f5f5f5;border-left:5px solid {{color:primary}};'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};font-weight:500;'>{{content}}</p></section>","templateHtml":"<section style='margin:14px 0;padding:14px 16px;background:#f5f5f5;border-left:5px solid {{color:primary}};'><p style='margin:0;font-size:16px;line-height:1.85;color:{{color:text}};font-weight:500;'>{{content}}</p></section>"},
    {"id":"scarlet-press-section-title","blockType":"section-title","name":"粗体小标题","previewHtml":"<section style='margin:22px 0 8px;padding-bottom:6px;border-bottom:2px solid {{color:primary}};'><h3 style='margin:0;color:{{color:primary}};font-size:20px;font-weight:800;'>{{content}}</h3></section>","templateHtml":"<section style='margin:22px 0 8px;padding-bottom:6px;border-bottom:2px solid {{color:primary}};'><h3 style='margin:0;color:{{color:primary}};font-size:20px;font-weight:800;'>{{content}}</h3></section>"},
    {"id":"scarlet-press-section-content","blockType":"section-content","name":"新闻正文","previewHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>","templateHtml":"<section style='margin:10px 0;'><p style='margin:0;font-size:16px;line-height:1.9;color:{{color:text}};text-align:justify;'>{{content}}</p></section>"},
    {"id":"scarlet-press-image","blockType":"image","name":"新闻配图","previewHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:2px;border:1px solid #ddd;'/>{{captionHtml}}</section>","templateHtml":"<section style='margin:18px 0;text-align:center;'><img src='{{imageUrl}}' alt='{{caption}}' style='max-width:100%;border-radius:2px;border:1px solid #ddd;'/>{{captionHtml}}</section>"},
    {"id":"scarlet-press-divider","blockType":"divider","name":"新闻分割线","previewHtml":"<section style='margin:20px 0;'><hr style='border:none;border-top:2px solid {{color:primary}};'/></section>","templateHtml":"<section style='margin:20px 0;'><hr style='border:none;border-top:2px solid {{color:primary}};'/></section>"},
    {"id":"scarlet-press-blockquote","blockType":"blockquote","name":"严肃引用","previewHtml":"<section style='margin:16px 0;padding:14px 16px;background:#f5f5f5;border-left:5px solid {{color:secondary}};'><blockquote style='margin:0;color:{{color:text}};font-weight:500;'>{{content}}</blockquote></section>","templateHtml":"<section style='margin:16px 0;padding:14px 16px;background:#f5f5f5;border-left:5px solid {{color:secondary}};'><blockquote style='margin:0;color:{{color:text}};font-weight:500;'>{{content}}</blockquote></section>"}
  ]$$::jsonb,
  330,
  true
)
on conflict (id) do update set
  name = excluded.name,
  thumbnail = excluded.thumbnail,
  categories = excluded.categories,
  color_family = excluded.color_family,
  has_hero_image = excluded.has_hero_image,
  color_scheme = excluded.color_scheme,
  block_styles = excluded.block_styles,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = now();
